# 包含外部规范
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart" # 排除 Riverpod 生成的代码
    - "**/*.freezed.dart"
  # 提升特定警告的等级
  errors:
    # 把“未使用的变量”从警告提升为错误，不改就编译不过
    unused_local_variable: error
    # 允许在特定场景忽略
    todo: ignore

linter:
  rules:
    # 强制在构造函数中使用 const
    prefer_const_constructors: true
    # 强制在每个类、方法上写文档注释（可选，根据团队严厉程度决定）
    public_member_api_docs: true
    # 允许单方法抽象类（Clean Architecture 接口需要）
    one_member_abstracts: false
    # 允许使用普通方法修改属性（Riverpod Notifier 常用模式）
    use_setters_to_change_properties: false
    # 关闭 Future 等待检查（减少 UI 回调中的 await）
    unawaited_futures: false
    discarded_futures: false